version:  '3.7'
services:
  db_app_laravel:
    image: mysql:8.0
    restart: on-failure
    volumes:
      - './db_data:/var/lib/mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app-laravel

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8000:80'
    depends_on:
      - app
    networks:
      - app-laravel

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - '.:/usr/src/app'
    user: 1000:1000
    networks:
      - app-laravel

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    networks:
      - app-laravel
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
networks:
  app-laravel:
    driver: bridge